//! Random well-typed Nix expressions, compared between evaluators.
//!
//! Expressions are generated by type (ints, bools, strings, lists of ints,
//! attribute sets of ints, int → int functions) with a scope of typed
//! variables, so most of them evaluate to a value instead of a type error.
//! `throw` is planted in lazy positions now and then: an evaluator that
//! forces something Nix doesn't (e.g. by speculative evaluation) turns a
//! value into an error.

use hegel::TestCase;
use hegel::generators as gs;
use nix_pbt::*;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Ty {
    Int,
    Bool,
    Str,
    List,
    Attrs,
    Fun,
}

const TYPES: [Ty; 6] = [Ty::Int, Ty::Bool, Ty::Str, Ty::List, Ty::Attrs, Ty::Fun];
const KEYS: &[&str] = &["a", "b", "c"];

struct Gen<'a> {
    tc: &'a TestCase,
    scope: Vec<(String, Ty)>,
    fresh: usize,
    budget: usize,
}

impl Gen<'_> {
    fn pick<T: Clone + Send + Sync + 'static>(&self, xs: Vec<T>) -> T {
        self.tc.draw_silent(gs::sampled_from(xs))
    }

    fn int(&self, lo: i64, hi: i64) -> i64 {
        self.tc
            .draw_silent(gs::integers::<i64>().min_value(lo).max_value(hi))
    }

    fn chance(&self, p: f64) -> bool {
        self.tc.draw_silent(gs::weighted_booleans(p))
    }

    fn var(&mut self) -> String {
        self.fresh += 1;
        format!("v{}", self.fresh)
    }

    fn vars_of(&self, ty: Ty) -> Vec<String> {
        self.scope
            .iter()
            .filter(|(_, t)| *t == ty)
            .map(|(n, _)| n.clone())
            .collect()
    }

    fn with_var<T>(&mut self, name: &str, ty: Ty, f: impl FnOnce(&mut Self) -> T) -> T {
        self.scope.push((name.to_string(), ty));
        let r = f(self);
        self.scope.pop();
        r
    }

    fn expr(&mut self, ty: Ty) -> String {
        if self.budget == 0 || self.chance(0.3) {
            return self.leaf(ty);
        }
        self.budget -= 1;
        // Constructs that work for every type.
        match self.int(0, 9) {
            0 => {
                let c = self.expr(Ty::Bool);
                let (a, b) = (self.expr(ty), self.expr(ty));
                return format!("(if {c} then {a} else {b})");
            }
            1 => {
                let t = self.pick(TYPES.to_vec());
                let v = self.var();
                let e = self.expr(t);
                let body = self.with_var(&v, t, |g| g.expr(ty));
                return format!("(let {v} = {e}; in {body})");
            }
            2 => {
                let c = self.expr(Ty::Bool);
                let e = self.expr(ty);
                return format!("(assert {c}; {e})");
            }
            3 => {
                // A lazily unused throw.
                let v = self.var();
                let body = self.with_var(&v, Ty::Int, |g| g.expr(ty));
                return format!("((({v}: {body})) (throw \"unused\"))");
            }
            _ => {}
        }
        match ty {
            Ty::Int => self.int_expr(),
            Ty::Bool => self.bool_expr(),
            Ty::Str => self.str_expr(),
            Ty::List => self.list_expr(),
            Ty::Attrs => self.attrs_expr(),
            Ty::Fun => self.fun_expr(),
        }
    }

    fn leaf(&mut self, ty: Ty) -> String {
        let vars = self.vars_of(ty);
        if !vars.is_empty() && self.chance(0.5) {
            return self.pick(vars);
        }
        if ty != Ty::Fun && self.chance(0.03) {
            return "(throw \"leaf\")".into();
        }
        match ty {
            Ty::Int => nix_int_literal(self.int(-3, 5)),
            Ty::Bool => self.pick(vec!["true", "false"]).into(),
            Ty::Str => {
                // Substrings of "é" can be invalid UTF-8, which Lix crashes
                // on when printing JSON.
                let mut leaves = vec!["", "a", "b", "ab", "1"];
                if !is_skipped("invalid-utf8-json") {
                    leaves.push("é");
                }
                nix_string_literal(self.pick(leaves))
            }
            Ty::List => {
                let n = self.int(0, 3) as usize;
                nix_list((0..n).map(|_| nix_int_literal(self.int(-2, 4))))
            }
            Ty::Attrs => {
                let n = self.int(0, 2) as usize;
                let fields: Vec<String> = (0..n)
                    .map(|i| format!("{} = {};", KEYS[i], self.int(-2, 4)))
                    .collect();
                format!("{{ {} }}", fields.join(" "))
            }
            Ty::Fun => {
                let v = self.var();
                format!("({v}: {v} + {})", self.int(0, 3))
            }
        }
    }

    fn int_expr(&mut self) -> String {
        match self.int(0, 11) {
            0 => format!("({} + {})", self.expr(Ty::Int), self.expr(Ty::Int)),
            1 => format!("({} - {})", self.expr(Ty::Int), self.expr(Ty::Int)),
            2 => format!("({} * {})", self.expr(Ty::Int), self.expr(Ty::Int)),
            3 => format!(
                "(builtins.div {} {})",
                self.expr(Ty::Int),
                self.expr(Ty::Int)
            ),
            4 => format!("(builtins.length {})", self.expr(Ty::List)),
            5 => format!("(builtins.stringLength {})", self.expr(Ty::Str)),
            6 => {
                let k = self.pick(KEYS.to_vec());
                format!("({}.{k} or {})", self.expr(Ty::Attrs), self.expr(Ty::Int))
            }
            7 => format!("(builtins.foldl' builtins.add 0 {})", self.expr(Ty::List)),
            8 => format!("(builtins.head {})", self.expr(Ty::List)),
            9 => format!("({} {})", self.expr(Ty::Fun), self.expr(Ty::Int)),
            10 => {
                let e = self.expr(Ty::Int);
                format!("(let r = builtins.tryEval {e}; in if r.success then r.value else -1)")
            }
            _ => format!(
                "(builtins.elemAt {} {})",
                self.expr(Ty::List),
                self.int(-1, 3)
            ),
        }
    }

    fn bool_expr(&mut self) -> String {
        match self.int(0, 9) {
            0 => {
                let t = self.pick(TYPES[..5].to_vec());
                format!("({} == {})", self.expr(t), self.expr(t))
            }
            1 => format!("({} < {})", self.expr(Ty::Int), self.expr(Ty::Int)),
            2 => format!("({} < {})", self.expr(Ty::Str), self.expr(Ty::Str)),
            3 => format!("(!{})", self.expr(Ty::Bool)),
            4 => format!("({} && {})", self.expr(Ty::Bool), self.expr(Ty::Bool)),
            5 => format!("({} || {})", self.expr(Ty::Bool), self.expr(Ty::Bool)),
            6 => format!("({} -> {})", self.expr(Ty::Bool), self.expr(Ty::Bool)),
            7 => format!("({} ? {})", self.expr(Ty::Attrs), self.pick(KEYS.to_vec())),
            8 => format!(
                "(builtins.elem {} {})",
                self.expr(Ty::Int),
                self.expr(Ty::List)
            ),
            _ => {
                let t = self.pick(TYPES.to_vec());
                let f = self.pick(vec![
                    "isInt",
                    "isString",
                    "isList",
                    "isAttrs",
                    "isFunction",
                    "isBool",
                ]);
                format!("(builtins.{f} {})", self.expr(t))
            }
        }
    }

    fn str_expr(&mut self) -> String {
        match self.int(0, 6) {
            0 => format!("({} + {})", self.expr(Ty::Str), self.expr(Ty::Str)),
            1 => format!(
                "\"${{{}}}-${{{}}}\"",
                self.expr(Ty::Str),
                self.expr(Ty::Str)
            ),
            2 => format!("(toString {})", self.expr(Ty::Int)),
            3 => format!(
                "(builtins.substring {} {} {})",
                self.expr(Ty::Int),
                self.expr(Ty::Int),
                self.expr(Ty::Str)
            ),
            4 => format!(
                "(builtins.concatStringsSep {} (map toString {}))",
                self.expr(Ty::Str),
                self.expr(Ty::List)
            ),
            5 => {
                let t = self.pick(TYPES.to_vec());
                format!("(builtins.typeOf {})", self.expr(t))
            }
            _ => format!(
                "(builtins.concatStringsSep \",\" (builtins.attrNames {}))",
                self.expr(Ty::Attrs)
            ),
        }
    }

    /// A function argument for map/filter/sort. When skipping the known
    /// fix divergence (it forces these even for empty lists), eta-expand
    /// it: forcing a lambda is harmless, and applying it is unchanged.
    fn higher_order_arg(&self, f: String) -> String {
        if is_skipped("empty-list-laziness") {
            format!("(x: {f} x)")
        } else {
            f
        }
    }

    fn list_expr(&mut self) -> String {
        match self.int(0, 7) {
            0 => {
                let n = self.int(0, 3) as usize;
                nix_list((0..n).map(|_| self.expr(Ty::Int)))
            }
            1 => format!("({} ++ {})", self.expr(Ty::List), self.expr(Ty::List)),
            2 => {
                let f = self.expr(Ty::Fun);
                format!("(map {} {})", self.higher_order_arg(f), self.expr(Ty::List))
            }
            3 => {
                let v = self.var();
                let body = self.with_var(&v, Ty::Int, |g| g.expr(Ty::Bool));
                format!("(builtins.filter ({v}: {body}) {})", self.expr(Ty::List))
            }
            4 => format!(
                "(builtins.genList {} {})",
                self.expr(Ty::Fun),
                self.int(0, 4)
            ),
            5 => format!("(builtins.sort builtins.lessThan {})", self.expr(Ty::List)),
            6 => format!("(builtins.attrValues {})", self.expr(Ty::Attrs)),
            _ => format!("(builtins.tail {})", self.expr(Ty::List)),
        }
    }

    fn attrs_expr(&mut self) -> String {
        match self.int(0, 5) {
            0 => {
                let n = self.int(0, 3) as usize;
                let fields: Vec<String> = (0..n)
                    .map(|i| format!("{} = {};", KEYS[i], self.expr(Ty::Int)))
                    .collect();
                format!("{{ {} }}", fields.join(" "))
            }
            1 => {
                // rec set: later keys may refer to earlier ones.
                let a = self.expr(Ty::Int);
                let b = self.with_var("a", Ty::Int, |g| g.expr(Ty::Int));
                format!("(rec {{ a = {a}; b = {b}; }})")
            }
            2 => format!("({} // {})", self.expr(Ty::Attrs), self.expr(Ty::Attrs)),
            3 => format!(
                "(builtins.removeAttrs {} [ \"{}\" ])",
                self.expr(Ty::Attrs),
                self.pick(KEYS.to_vec())
            ),
            4 => format!(
                "(builtins.mapAttrs (n: v: {} v) {})",
                self.expr(Ty::Fun),
                self.expr(Ty::Attrs)
            ),
            _ => format!(
                "(builtins.listToAttrs (map (x: {{ name = builtins.substring 0 1 \"abc\"; value = x; }}) {}))",
                self.expr(Ty::List)
            ),
        }
    }

    fn fun_expr(&mut self) -> String {
        match self.int(0, 2) {
            0 => {
                let v = self.var();
                let body = self.with_var(&v, Ty::Int, |g| g.expr(Ty::Int));
                format!("({v}: {body})")
            }
            1 => {
                // Composition.
                let (f, g) = (self.expr(Ty::Fun), self.expr(Ty::Fun));
                let v = self.var();
                format!("({v}: {f} ({g} {v}))")
            }
            _ => {
                // Formals with defaults that refer to an outer variable.
                let v = self.var();
                let attrs = self.expr(Ty::Attrs);
                format!("({v}: ({{ a ? 1, b ? {v}, ... }}: a + b) {attrs})")
            }
        }
    }
}

#[hegel::composite]
fn exprs(tc: &TestCase) -> String {
    let budget = tc.draw(gs::integers::<usize>().min_value(1).max_value(25));
    let ty = TYPES[tc.draw(gs::integers::<usize>().max_value(4))];
    let mut g = Gen {
        tc,
        scope: Vec::new(),
        fresh: 0,
        budget,
    };
    g.expr(ty)
}

#[hegel::test]
fn random_expressions(tc: TestCase) {
    let expr = tc.draw(exprs());
    let out = check(&expr, Expect::Unspecified);
    tc.event(match out {
        Outcome::Value(_) => "value",
        Outcome::Error(_) => "error",
        _ => "other",
    });
}

/// Laziness: wrapping an expression in a binding that is never used, or in
/// a list whose elements aren't forced, never changes whether it succeeds.
#[hegel::test]
fn unused_throws_are_not_forced(tc: TestCase) {
    let expr = tc.draw(exprs());
    let wrapped = tc.draw(gs::sampled_from(vec![
        format!("let unused = throw \"x\"; in {expr}"),
        format!("(_: {expr}) (throw \"x\")"),
        format!("builtins.seq (builtins.length [ (throw \"x\") ]) ({expr})"),
        format!("({{ a = {expr}; b = throw \"x\"; }}).a"),
        format!("(builtins.head [ ({expr}) (throw \"x\") ])"),
        format!("(if true then {expr} else throw \"x\")"),
        format!("(builtins.attrValues {{ a = {expr}; }})"),
    ]));
    let plain = check(&expr, Expect::Unspecified);
    let expect = match &plain {
        Outcome::Value(v) if !wrapped.starts_with("(builtins.attrValues") => {
            Expect::Value(v.clone())
        }
        Outcome::Value(v) => Expect::Value(serde_json::json!([v])),
        Outcome::Error(_) => Expect::Error,
        _ => Expect::Unspecified,
    };
    check(&wrapped, expect);
}
